import { Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-col min-h-screen">
        <header className="border-b text-center text-gray-500 mb-180 w-full font-bold text-xl p-2">
            <span className="text-lime-500">OSS</span> The home of <span className="text-lime-500">OPEN SOURCE</span> 
          </header>
          <main className="flex-1 flex">
         
            {/* <Sidebar /> */}
            <div className="flex-1">
              {children}
            </div>
          </main>
          <footer className="border-t p-8 text-center text-gray-500 mt-20 w-full">
            &copy; Rookie 2024/25 ALL rights reserved
          </footer>
        </div>
      </body>
    </html>
  );
}
